general:
  iflowName: flow1
  iflowVersion: 1.0.1

steps:
  deployIntegrationArtifact:
    cpiCredentialsId: roverpocOauthCred
    integrationFlowId: flow2
    integrationFlowVersion: 1.0.1
    platform: cf
    host: https://roverpoc.it-accd002.cfapps.sap.hana.ondemand.com
    oAuthTokenProviderUrl: https://roverpoc.authentication.sap.hana.ondemand.com/oauth/token
